-- CreateTable
CREATE TABLE `setting_webs` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `judul_web` VARCHAR(191) NOT NULL,
    `deskripsi_web` VARCHAR(191) NOT NULL,
    `keyword` VARCHAR(191) NOT NULL,
    `og_image` VARCHAR(191) NULL,
    `logo_header` VARCHAR(191) NULL,
    `logo_footer` VARCHAR(191) NULL,
    `logo_favicon` VARCHAR(191) NULL,
    `logo_banner` VARCHAR(191) NULL,
    `logo_cs` VARCHAR(191) NULL,
    `url_wa` VARCHAR(191) NOT NULL,
    `url_ig` VARCHAR(191) NOT NULL,
    `url_tiktok` VARCHAR(191) NOT NULL,
    `url_youtube` VARCHAR(191) NOT NULL,
    `url_fb` VARCHAR(191) NOT NULL,
    `kbrstore_api` VARCHAR(191) NOT NULL,
    `slogan_web` VARCHAR(191) NOT NULL,
    `snk` VARCHAR(191) NOT NULL,
    `privacy` VARCHAR(191) NOT NULL,
    `warna1` VARCHAR(191) NOT NULL,
    `warna2` VARCHAR(191) NOT NULL,
    `warna3` VARCHAR(191) NOT NULL,
    `warna4` VARCHAR(191) NOT NULL,
    `warna5` VARCHAR(191) NOT NULL,
    `harga_gold` VARCHAR(191) NOT NULL,
    `harga_platinum` VARCHAR(191) NOT NULL,
    `tripay_api` VARCHAR(191) NULL,
    `tripay_merchant_code` VARCHAR(191) NULL,
    `tripay_private_key` VARCHAR(191) NULL,
    `duitku_key` VARCHAR(191) NULL,
    `duitku_merchant` VARCHAR(191) NULL,
    `username_digi` VARCHAR(191) NULL,
    `api_key_digi` VARCHAR(191) NULL,
    `apigames_secret` VARCHAR(191) NULL,
    `apigames_merchant` VARCHAR(191) NULL,
    `vip_apiid` VARCHAR(191) NULL,
    `vip_apikey` VARCHAR(191) NULL,
    `digi_seller_user` VARCHAR(191) NULL,
    `digi_seller_key` VARCHAR(191) NULL,
    `nomor_admin` VARCHAR(191) NULL,
    `wa_key` VARCHAR(191) NULL,
    `wa_number` VARCHAR(191) NULL,
    `ovo_admin` VARCHAR(191) NULL,
    `ovo1_admin` VARCHAR(191) NULL,
    `gopay_admin` VARCHAR(191) NULL,
    `gopay1_admin` VARCHAR(191) NULL,
    `dana_admin` VARCHAR(191) NULL,
    `shopeepay_admin` VARCHAR(191) NULL,
    `bca_admin` VARCHAR(191) NULL,
    `mandiri_admin` VARCHAR(191) NULL,
    `logo_ceo` VARCHAR(191) NULL,
    `sejarah` VARCHAR(191) NOT NULL,
    `sejarah_1` VARCHAR(191) NOT NULL,
    `visi` VARCHAR(191) NOT NULL,
    `misi` VARCHAR(191) NOT NULL,
    `nama_ceo` VARCHAR(191) NOT NULL,
    `deskripsi_ceo` VARCHAR(191) NOT NULL,
    `nama_bagan` VARCHAR(191) NOT NULL,
    `alamat` VARCHAR(191) NOT NULL,
    `telp` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
